/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void fill_click1(GButton source, GEvent event) { //_CODE_:btn_fill:241519:
  fill();
} //_CODE_:btn_fill:241519:

public void button1_click1(GButton source, GEvent event) { //_CODE_:btn_start:428180:

} //_CODE_:btn_start:428180:

public void open_click1(GButton source, GEvent event) { //_CODE_:btn_open:719474:

  openDataFolder();
} //_CODE_:btn_open:719474:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Haptic Mice - Stage 2");
  lbl_min_freq = new GLabel(this, 20, 20, 120, 20);
  lbl_min_freq.setTextAlign(GAlign.RIGHT, GAlign.MIDDLE);
  lbl_min_freq.setText("min freq:");
  lbl_min_freq.setOpaque(false);
  lbl_dur1 = new GLabel(this, 240, 20, 80, 20);
  lbl_dur1.setTextAlign(GAlign.RIGHT, GAlign.MIDDLE);
  lbl_dur1.setText("duration 1:");
  lbl_dur1.setOpaque(false);
  lbl_wait = new GLabel(this, 20, 60, 120, 20);
  lbl_wait.setTextAlign(GAlign.RIGHT, GAlign.MIDDLE);
  lbl_wait.setText("wait time:");
  lbl_wait.setOpaque(false);
  lbl_max_freq = new GLabel(this, 20, 100, 120, 20);
  lbl_max_freq.setTextAlign(GAlign.RIGHT, GAlign.MIDDLE);
  lbl_max_freq.setText("max freq:");
  lbl_max_freq.setOpaque(false);
  lbl_dur2 = new GLabel(this, 240, 100, 80, 20);
  lbl_dur2.setTextAlign(GAlign.RIGHT, GAlign.MIDDLE);
  lbl_dur2.setText("duration 2:");
  lbl_dur2.setOpaque(false);
  lbl_open_door = new GLabel(this, 20, 140, 120, 20);
  lbl_open_door.setTextAlign(GAlign.RIGHT, GAlign.MIDDLE);
  lbl_open_door.setText("open door:");
  lbl_open_door.setOpaque(false);
  lbl_time_response = new GLabel(this, 20, 180, 120, 20);
  lbl_time_response.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lbl_time_response.setText("time to response:");
  lbl_time_response.setOpaque(false);
  lbl_repeats = new GLabel(this, 60, 220, 80, 20);
  lbl_repeats.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lbl_repeats.setText("repeats:");
  lbl_repeats.setOpaque(false);
  lbl_time_experiments = new GLabel(this, 20, 260, 120, 20);
  lbl_time_experiments.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lbl_time_experiments.setText("Time betwen exp:");
  lbl_time_experiments.setOpaque(false);
  lbl_experiment_name = new GLabel(this, 20, 300, 120, 20);
  lbl_experiment_name.setTextAlign(GAlign.RIGHT, GAlign.MIDDLE);
  lbl_experiment_name.setText("Experiment name:");
  lbl_experiment_name.setOpaque(false);
  lbl_if_fail = new GLabel(this, 20, 340, 120, 20);
  lbl_if_fail.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  lbl_if_fail.setText("if fail,close door:");
  lbl_if_fail.setOpaque(false);
  fld_min_freq = new GTextField(this, 140, 20, 90, 20, G4P.SCROLLBARS_NONE);
  fld_min_freq.setOpaque(true);
  fld_time1 = new GTextField(this, 320, 20, 90, 20, G4P.SCROLLBARS_NONE);
  fld_time1.setOpaque(true);
  fld_wait_time = new GTextField(this, 140, 60, 90, 20, G4P.SCROLLBARS_NONE);
  fld_wait_time.setOpaque(true);
  fld_max_freq = new GTextField(this, 140, 100, 90, 20, G4P.SCROLLBARS_NONE);
  fld_max_freq.setOpaque(true);
  fld_time2 = new GTextField(this, 320, 100, 90, 20, G4P.SCROLLBARS_NONE);
  fld_time2.setOpaque(true);
  fld_door_time = new GTextField(this, 140, 140, 90, 20, G4P.SCROLLBARS_NONE);
  fld_door_time.setOpaque(true);
  fld_repeats = new GTextField(this, 140, 220, 90, 20, G4P.SCROLLBARS_NONE);
  fld_repeats.setOpaque(true);
  fld_time_experiments = new GTextField(this, 140, 260, 90, 20, G4P.SCROLLBARS_NONE);
  fld_time_experiments.setOpaque(true);
  fld_name = new GTextField(this, 140, 300, 90, 20, G4P.SCROLLBARS_NONE);
  fld_name.setOpaque(true);
  fld_close_door = new GTextField(this, 140, 340, 90, 20, G4P.SCROLLBARS_NONE);
  fld_close_door.setOpaque(true);
  btn_fill = new GButton(this, 330, 160, 80, 30);
  btn_fill.setText("Fill");
  btn_fill.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  btn_fill.addEventHandler(this, "fill_click1");
  btn_start = new GButton(this, 330, 210, 80, 30);
  btn_start.setText("Start");
  btn_start.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  btn_start.addEventHandler(this, "button1_click1");
  btn_open = new GButton(this, 330, 260, 80, 30);
  btn_open.setText("Open..");
  btn_open.addEventHandler(this, "open_click1");
  fld_response_time = new GTextField(this, 140, 180, 90, 20, G4P.SCROLLBARS_NONE);
  fld_response_time.setOpaque(true);
}

// Variable declarations 
// autogenerated do not edit
GLabel lbl_min_freq; 
GLabel lbl_dur1; 
GLabel lbl_wait; 
GLabel lbl_max_freq; 
GLabel lbl_dur2; 
GLabel lbl_open_door; 
GLabel lbl_time_response; 
GLabel lbl_repeats; 
GLabel lbl_time_experiments; 
GLabel lbl_experiment_name; 
GLabel lbl_if_fail; 
GTextField fld_min_freq; 
GTextField fld_time1; 
GTextField fld_wait_time; 
GTextField fld_max_freq; 
GTextField fld_time2; 
GTextField fld_door_time; 
GTextField fld_repeats; 
GTextField fld_time_experiments; 
GTextField fld_name; 
GTextField fld_close_door; 
GButton btn_fill; 
GButton btn_start; 
GButton btn_open; 
GTextField fld_response_time; 
