/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void dropList1_click1(GDropList source, GEvent event) { //_CODE_:portList:756398:
  println("portList - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:portList:756398:

public void btnOn_click1(GButton source, GEvent event) { //_CODE_:btnOn:494070:
setArduino();
run=true;
  thread("runTest");
} //_CODE_:btnOn:494070:

public void btnOff_click(GButton source, GEvent event) { //_CODE_:btnOff:503171:
  run=false;
} //_CODE_:btnOff:503171:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  portList = new GDropList(this, 20, 20, 260, 80, 3, 10);
  portList.setItems(Arduino.list(), 0);
  portList.addEventHandler(this, "dropList1_click1");
  fldFreq = new GTextField(this, 20, 60, 260, 30, G4P.SCROLLBARS_NONE);
  fldFreq.setOpaque(true);
  btnOn = new GButton(this, 20, 120, 80, 30);
  btnOn.setText("On");
  btnOn.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  btnOn.addEventHandler(this, "btnOn_click1");
  btnOff = new GButton(this, 200, 120, 80, 30);
  btnOff.setText("OFf");
  btnOff.setLocalColorScheme(GCScheme.RED_SCHEME);
  btnOff.addEventHandler(this, "btnOff_click");
}

// Variable declarations 
// autogenerated do not edit
GDropList portList; 
GTextField fldFreq; 
GButton btnOn; 
GButton btnOff; 
